// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaTaWc0HFnyBYw8EPQ_HF6Z1khur-L3M',
    appId: '1:811639391152:web:c177c9b252601f40f04c75',
    messagingSenderId: '811639391152',
    projectId: 'flutter-firebase-auth-4e9c0',
    authDomain: 'flutter-firebase-auth-4e9c0.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-4e9c0.firebasestorage.app',
    measurementId: 'G-J8V9DF54FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2x3tMia5iTOOfVZ6wEY84n24yZO2QIco',
    appId: '1:811639391152:android:eb6dced28bcb4ea0f04c75',
    messagingSenderId: '811639391152',
    projectId: 'flutter-firebase-auth-4e9c0',
    storageBucket: 'flutter-firebase-auth-4e9c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD01GxXJorRStPX1kMKWr5FJrltbw_wx9k',
    appId: '1:811639391152:ios:44a65526ae314f19f04c75',
    messagingSenderId: '811639391152',
    projectId: 'flutter-firebase-auth-4e9c0',
    storageBucket: 'flutter-firebase-auth-4e9c0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD01GxXJorRStPX1kMKWr5FJrltbw_wx9k',
    appId: '1:811639391152:ios:44a65526ae314f19f04c75',
    messagingSenderId: '811639391152',
    projectId: 'flutter-firebase-auth-4e9c0',
    storageBucket: 'flutter-firebase-auth-4e9c0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdaTaWc0HFnyBYw8EPQ_HF6Z1khur-L3M',
    appId: '1:811639391152:web:2ff99a61413041e5f04c75',
    messagingSenderId: '811639391152',
    projectId: 'flutter-firebase-auth-4e9c0',
    authDomain: 'flutter-firebase-auth-4e9c0.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-4e9c0.firebasestorage.app',
    measurementId: 'G-TYRFV0NDRB',
  );
}
