name: pizza_repository
description: "The Repo that handles pizzas"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # equatable: ^2.0.7
  # firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  # rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true