// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKr1VGxPx16-dD-gikV9l7Nh35493KYLs',
    appId: '1:393495805853:web:cbec0c58e114774b1b3974',
    messagingSenderId: '393495805853',
    projectId: 'bloc-photo-library-001',
    authDomain: 'bloc-photo-library-001.firebaseapp.com',
    storageBucket: 'bloc-photo-library-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3HuYwvsqDaq_73rKfM6II7bytwqnyqpo',
    appId: '1:393495805853:android:91afd74cd89a91bc1b3974',
    messagingSenderId: '393495805853',
    projectId: 'bloc-photo-library-001',
    storageBucket: 'bloc-photo-library-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFobvDWiBW7cAAYHLFraJVvDbsZn3y2Yc',
    appId: '1:393495805853:ios:ed31231ff41d09331b3974',
    messagingSenderId: '393495805853',
    projectId: 'bloc-photo-library-001',
    storageBucket: 'bloc-photo-library-001.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFobvDWiBW7cAAYHLFraJVvDbsZn3y2Yc',
    appId: '1:393495805853:ios:ed31231ff41d09331b3974',
    messagingSenderId: '393495805853',
    projectId: 'bloc-photo-library-001',
    storageBucket: 'bloc-photo-library-001.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKr1VGxPx16-dD-gikV9l7Nh35493KYLs',
    appId: '1:393495805853:web:d03d0fe657e68c361b3974',
    messagingSenderId: '393495805853',
    projectId: 'bloc-photo-library-001',
    authDomain: 'bloc-photo-library-001.firebaseapp.com',
    storageBucket: 'bloc-photo-library-001.appspot.com',
  );
}
